
package web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeSoapServiceService", targetNamespace = "http://web/", wsdlLocation = "http://localhost:9632/testservice?wsdl")
public class EmployeeSoapServiceService
    extends Service
{

    private final static URL EMPLOYEESOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEESOAPSERVICESERVICE_EXCEPTION;
    private final static QName EMPLOYEESOAPSERVICESERVICE_QNAME = new QName("http://web/", "EmployeeSoapServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9632/testservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEESOAPSERVICESERVICE_WSDL_LOCATION = url;
        EMPLOYEESOAPSERVICESERVICE_EXCEPTION = e;
    }

    public EmployeeSoapServiceService() {
        super(__getWsdlLocation(), EMPLOYEESOAPSERVICESERVICE_QNAME);
    }

    public EmployeeSoapServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEESOAPSERVICESERVICE_QNAME, features);
    }

    public EmployeeSoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEESOAPSERVICESERVICE_QNAME);
    }

    public EmployeeSoapServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEESOAPSERVICESERVICE_QNAME, features);
    }

    public EmployeeSoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeSoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeSoapService
     */
    @WebEndpoint(name = "EmployeeSoapServicePort")
    public EmployeeSoapService getEmployeeSoapServicePort() {
        return super.getPort(new QName("http://web/", "EmployeeSoapServicePort"), EmployeeSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeSoapService
     */
    @WebEndpoint(name = "EmployeeSoapServicePort")
    public EmployeeSoapService getEmployeeSoapServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web/", "EmployeeSoapServicePort"), EmployeeSoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEESOAPSERVICESERVICE_EXCEPTION!= null) {
            throw EMPLOYEESOAPSERVICESERVICE_EXCEPTION;
        }
        return EMPLOYEESOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
