
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeSoapService", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeSoapService {


    /**
     * 
     * @return
     *     returns web.GroupOfEmployee
     */
    @WebMethod
    @WebResult(name = "GroupOfEmployee", partName = "GroupOfEmployee")
    @Action(input = "http://web/EmployeeSoapService/readAllRequest", output = "http://web/EmployeeSoapService/readAllResponse")
    public GroupOfEmployee readAll();

    /**
     * 
     * @param employee
     */
    @WebMethod
    @Action(input = "http://web/EmployeeSoapService/createNewEmployeeRequest", output = "http://web/EmployeeSoapService/createNewEmployeeResponse")
    public void createNewEmployee(
        @WebParam(name = "Employee", partName = "Employee")
        Employee employee);

}
