
------CUSTOMER SEQUENCE AND TABLE-----
create sequence CUSTOMER_ID_SEQ start with 5200 increment by 1;

create table MYBANK_APP_CUSTOMER(
CUSTOMER_ID INT,
CUSTOMER_NAME VARCHAR2(255) NOT NULL,
CUSTOMER_ADDRESS VARCHAR2(255) NOT NULL,
CUSTOMER_STATUS VARCHAR2(255) NOT NULL,
CUSTOMER_CONTACT NUMBER(10) NOT NULL,
USERNAME VARCHAR2(255) NOT NULL, --UNIQUWE
PASSWORD VARCHAR2(255) NOT NULL
);
--PAYEE MAPPED TO ACCOUNT NUMBER
alter table MYBANK_APP_CUSTOMER add constraint CUSTOMER_ID_SEQ primary key(CUSTOMER_ID);
ALTER TABLE MYBANK_APP_CUSTOMER ADD UNIQUE (USERNAME);

insert into MYBANK_APP_CUSTOMER values(CUSTOMER_ID_SEQ.nextval,'Abhishek','Kasargod','Active',9874563210,'abhis01','01abhis');
insert into MYBANK_APP_CUSTOMER values(CUSTOMER_ID_SEQ.nextval,'Amal','Kannur','Active',9874563980,'amal01','01amal');

----KYC TABLE WITH SEQUENCE--

create sequence KYC_SEQ start with 6800 increment by 1;
 
CREATE TABLE MYBANK_APP_KYC(
KYC_NUMBER INT,
CUSTOMER_ID INT NOT NULL,
KYC_PAN VARCHAR2(255) NOT NULL,
KYC_AADHAAR NUMBER(16) NOT NULL,
KYC_STATUS VARCHAR2(255) NOT NULL,
FOREIGN KEY(CUSTOMER_ID) REFERENCES MYBANK_APP_CUSTOMER(CUSTOMER_ID) on delete cascade
);
  
alter table MYBANK_APP_KYC add constraint KYC_SEQ primary key(KYC_NUMBER);


insert into MYBANK_APP_KYC VALUES(KYC_SEQ.nextval,5200,'HANPA6997L',8569748925478963,'APPROVED');
insert into MYBANK_APP_KYC VALUES(KYC_SEQ.nextval,5201,'HCNPA8997L',8569748925478745,'APPROVED');
--------ACCOUNT TABLEE WITH SEQUENCE---------
create sequence ACC_SEQ start with 9800 increment by 1;
 
CREATE TABLE MYBANK_APP_ACCOUNT(
ACCOUNT_ID INT,
CUSTOMER_ID INT,
ACCOUNT_TYPE VARCHAR(50) NOT NULL,
ACCOUNT_NUMBER VARCHAR(225) NOT NULL UNIQUE,
ACCOUNT_STATUS VARCHAR NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES MYBANK_APP_CUSTOMER(CUSTOMER_ID) on delete cascade
);

alter table MYBANK_APP_ACCOUNT add constraint ACC_SEQ  primary key(ACCOUNT_ID);

INSERT INTO MYBANK_APP_ACCOUNT VALUES(ACC_SEQ.nextval,5200,'SALERY',8596336,'ACTIVE');
INSERT INTO MYBANK_APP_ACCOUNT VALUES(ACC_SEQ.nextval,5201,'SAVINGS',7396336,'ACTIVE');


------DEPOSIT TABLE WITH SEQUENCE-----
create sequence DEPOSIT_SEQ start with 100 increment by 1;
 
CREATE TABLE MYBANK_APP_DEPOSITAVAILABLE(
DEPOSIT_ID INT,
DEPOSIT_NAME VARCHAR2(255) NOT NULL,
DEPOSIT_ROI DECIMAL(15,2) NOT NULL,
DEPOSIT_TYPE VARCHAR(255) NOT NULL,
DEPOSIT_DESCRIPTION CLOB NOT NULL
);
 
alter table MYBANK_APP_DEPOSITAVAILABLE add constraint DEPOSIT_SEQ primary key(DEPOSIT_ID);

INSERT INTO MYBANK_APP_DEPOSITAVAILABLE VALUES(DEPOSIT_SEQ.NEXTVAL,'FIXED DEPOSIT',6.25,'TIME DEPOSIT','Deposited for the future'); 

INSERT INTO MYBANK_APP_DEPOSITAVAILABLE VALUES(DEPOSIT_SEQ.NEXTVAL,'RECURRING DEPOSIT',7.25,'NEW DEPOSIT','Deposited for the future'); 

---TABLE FOR DEPOSIT AVAILED WITH SEQUENCE--------
CREATE SEQUENCE DEPOSITAVAIL_SEQ START WITH 4000 INCREMENT BY 1;
 
CREATE TABLE MYBANK_APP_DEPOSITAVAILED(
DEPOSIT_AVAIL_ID INT,
CUSTOMER_ID INT NOT NULL,
DEPOSIT_ID INT NOT NULL,
DEPOSITED_AMOUNT DECIMAL(15,2) NOT NULL,
DEPOSIT_DURATION INT NOT NULL,
DEPOSIT_MATURITY DATE NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES MYBANK_APP_CUSTOMER(CUSTOMER_ID) on delete cascade,
FOREIGN KEY (DEPOSIT_ID) REFERENCES MYBANK_APP_DEPOSITAVAILABLE(DEPOSIT_ID) on delete cascade
);

alter table MYBANK_APP_DEPOSITAVAILED add constraint DEPOSITAVAIL_SEQ primary key(DEPOSIT_AVAIL_ID);
INSERT INTO MYBANK_APP_DEPOSITAVAILED VALUES (DEPOSITAVAIL_SEQ.NEXTVAL,5200,100,450000,5,'01-FEB-2026');

INSERT INTO MYBANK_APP_DEPOSITAVAILED VALUES (DEPOSITAVAIL_SEQ.NEXTVAL,5201,101,550000,6,'01-MARCH-2026');

-----INSURANCE TABLE WITH SEQUENCE---
CREATE SEQUENCE INSURANCE_ID_SEQ START WITH 6500 INCREMENT BY 1;

CREATE TABLE MYBANK_APP_INSURANCEAVAILABLE(
INSURANCE_ID INT ,
INSURANCE_TYPE VARCHAR2(50) NOT NULL,
INSURANCE_NAME VARCHAR2(255)NOT NULL,
INSURANCE_KEY_BENEFITS CLOB NOT NULL,
INSURANCE_LIFETIME INT NOT NULL);

alter table MYBANK_APP_INSURANCEAVAILABLE add constraint INSURANCE_ID_SEQ  primary key(INSURANCE_ID);
  
  INSERT INTO MYBANK_APP_IN

-----INSIARANCE AVAIL TABLE WITH SEQUENCE----
CREATE SEQUENCE INSURANCE_AVAIL_SEQ START WITH 8000 INCREMENT BY 1;

CREATE TABLE MYBANK_APP_INSURANCEAVAILED(
INSURANCE_AVAIL_ID INT,
CUSTOMER_ID INT ,
INSURANCE_ID INT ,
INSURANCE_COVERAGE DECIMAL(15,2) NOT NULL,
INSURANCE_PREMIUM DECIMAL(15,2) NOT NULL,
FOREIGN KEY(CUSTOMER_ID) REFERENCES MYBANK_APP_CUSTOMER(CUSTOMER_ID) on delete cascade,
FOREIGN KEY(INSURANCE_ID) REFERENCES MYBANK_APP_INSURANCEAVAILABLE(INSURANCE_ID) on delete cascade
);

alter table MYBANK_APP_INSURANCEAVAILED add constraint INSURANCE_AVAIL_ID_SEQ  primary key(INSURANCE_AVAIL_ID);

--------TABLE FOR DEBIT WITH SEQUENCE----
create sequence DEBIT_SEQ start with 2000 increment by 1;
 
CREATE TABLE MYBANK_APP_DebitCard(
DEBITCARD_NUMBER NUMBER(20),
ACCOUNT_ID INT,
DEBITCARD_CVV INT NOT NULL,
DEBITCARD_EXPIRY DATE NOT NULL,
DEBITCARD_STATUS NUMBER(4) NOT NULL,
DEBITCARD_DOMESTIC_LIMIT NUMBER(20) NOT NULL,
DEBITCARD_INTERNATIONAL_LIMIT NUMBER(20) NOT NULL,
FOREIGN KEY(ACCOUNT_ID) REFERENCES  MYBANK_APP_ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE
);
ALTER TABLE  MYBANK_APP_DebitCard ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES  MYBANK_APP_CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE;
ALTER TABLE  MYBANK_APP_DebitCard ADD FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES  MYBANK_APP_ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE;
alter table MYBANK_APP_DebitCard add constraint DEBIT_SEQ  primary key(DEBITCARD_NUMBER);

---TABLE FOR LOAN AVAILABLE WITH SEQ-----
create sequence LOAN_SEQ start with 1500 increment by 1;

create table MYBANK_APP_LOANAVAILABLE(
loan_number int,
loan_type varchar2(255) not null,
loan_name varchar(255) not null,
loan_description clob not null,
loan_roi decimal(15,2) not  null
);

alter table MYBANK_APP_LOANAVAILABLE add constraint LOAN_SEQ  primary key(loan_number);

------LOAN AVAILED--------
create sequence LOAN_AVAILED_SEQ start with 100 increment by 1;

create table MYBANK_APP_LOANAVAILED(
loan_avail_number int,
customer_number int,
loan_number int,
loan_amount decimal(15,2) not null,
loan_emi decimal(15,2) not null,
loan_tenure int not null,
FOREIGN KEY (customer_number) REFERENCES MYBANK_APP_Customer(customer_Id) on delete cascade,
FOREIGN KEY (loan_number) REFERENCES MYBANK_APP_LOANAVAILABLE(loan_number) on delete cascade
);

alter table MYBANK_APP_LOANAVAILED add constraint LOAN_AVAILED_SEQ  primary key(loan_avail_number);

---TRANSACTION TABLE WITH SEQUENCE-----

create sequence transactionid_seq start with 9000 increment by 1;

CREATE TABLE MYBANK_APP_Transaction (
    transaction_id INT,
    account_id INT,
    transaction_type VARCHAR(50) not null,
    transaction_from VARCHAR(255) not null,
    transaction_to VARCHAR(255) not null,
    transaction_date DATE not null,
    transaction_amount DECIMAL(15,2) not null,
    transaction_status VARCHAR(50) not null,
    FOREIGN KEY (account_id) REFERENCES MYBANK_APP_Account(account_id) on delete cascade
);
ALTER TABLE  MYBANK_APP_Transaction ADD FOREIGN KEY(TRANSACTION_FROM) REFERENCES  MYBANK_APP_ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE;

ALTER TABLE  MYBANK_APP_Transaction ADD FOREIGN KEY(TRANSACTION_TO) REFERENCES  MYBANK_APP_ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE;

alter table MYBANK_APP_Transaction add constraint transactionid_seq  primary key(transaction_id);

-----------PAYEE TABLE WITH SEQUENCE------
create sequence payee_seq start with 100 increment by 1;

CREATE TABLE MYBANK_APP_Payee (
    payee_id INT ,
    customer_id INT,
    account_id INT,
    payee_name VARCHAR(255) not null,
    FOREIGN KEY (customer_id) REFERENCES MYBANK_APP_Customer(customer_id) on delete cascade,
    FOREIGN KEY (account_id) REFERENCES MYBANK_APP_Account(account_id) on delete cascade
); 

alter table MYBANK_APP_Payee add constraint payee_seq  primary key(payee_id);
ALTER TABLE  MYBANK_APP_PAYEE ADD FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES  MYBANK_APP_ACCOUNT(ACCOUNT_NUMBER) ON DELETE CASCADE;


