
package web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapAccountService", targetNamespace = "http://web/", wsdlLocation = "http://localhost:7002/soapservices?wsdl")
public class SoapAccountService
    extends Service
{

    private final static URL SOAPACCOUNTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPACCOUNTSERVICE_EXCEPTION;
    private final static QName SOAPACCOUNTSERVICE_QNAME = new QName("http://web/", "SoapAccountService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7002/soapservices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPACCOUNTSERVICE_WSDL_LOCATION = url;
        SOAPACCOUNTSERVICE_EXCEPTION = e;
    }

    public SoapAccountService() {
        super(__getWsdlLocation(), SOAPACCOUNTSERVICE_QNAME);
    }

    public SoapAccountService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPACCOUNTSERVICE_QNAME, features);
    }

    public SoapAccountService(URL wsdlLocation) {
        super(wsdlLocation, SOAPACCOUNTSERVICE_QNAME);
    }

    public SoapAccountService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPACCOUNTSERVICE_QNAME, features);
    }

    public SoapAccountService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapAccountService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapAccount
     */
    @WebEndpoint(name = "SoapAccountPort")
    public SoapAccount getSoapAccountPort() {
        return super.getPort(new QName("http://web/", "SoapAccountPort"), SoapAccount.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapAccount
     */
    @WebEndpoint(name = "SoapAccountPort")
    public SoapAccount getSoapAccountPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web/", "SoapAccountPort"), SoapAccount.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPACCOUNTSERVICE_EXCEPTION!= null) {
            throw SOAPACCOUNTSERVICE_EXCEPTION;
        }
        return SOAPACCOUNTSERVICE_WSDL_LOCATION;
    }

}
